### ISSUE TITLE
auto load gifs on scroll to bottom

### ISSUE THREAD

**Issue by alok722** [alok722/react-gif-finder#1]
As of now, user have to click on Load more button to load more gifs, instead I want to auto load as soon as the users reches the bottom.

**Comment by tanvimehta** [comment]
I'd like to work on this issue if you don't mind.

**Comment by mehdirajani5** [comment]
@alok722 
Issue Still Exist?

**Comment by alok722** [comment]
> @alok722
> Issue Still Exist?

Yes, @mehdirajani5

**Comment by mehdirajani5** [comment]
I am on it now

**Comment by mehdirajani5** [comment]
@alok722 
I am on it now.

**Comment by mehdirajani5** [comment]
@alok722 
Some times getting this error.  Unable to fetch data

![Screenshot 2020-10-28 at 1 01 27 PM](https://user-images.githubusercontent.com/17649381/97408594-1fe8dd00-191e-11eb-81a3-bed3743778da.png)

Can you tell me whats wrong with it.

**Comment by mehdirajani5** [comment]
@alok722  Issue fixed

**Comment by alok722** [comment]
#2 this PR closes this issue.
